title: Anton Evers - PGP
description: PGP key to send me secure email
sitename: Anton Evers
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
